### ISSUE TITLE
Suggest increase the tip in the readme doc

### ISSUE THREAD

**Issue by chsword** [aspnet/vsweb-docs#17]
Suggestions to increase the following：
If need to deploy to the IIS, need to install the http://www.iis.net/downloads/microsoft/url-rewrite

**Comment by madskristensen** [comment]
I thought the URL rewrite module was installed by default in IIS 7.5. What version of IIS are you using that doesn't have it?

**Comment by chsword** [comment]
IIS 8.5 & IIS 10.0

I install the iis by windows ,but not WPI.

**Comment by madskristensen** [comment]
Thanks. I added the link
